global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'menu_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['menu-service:8080']
        labels:
          application: 'Menu Service Application'