spring:
  cloud.config.server.git:
    clone-on-start: true
    username: MrShims
    password: ${GIT_PASSWORD}
    uri: https://github.com/MrShims/Config-server

  application:
    name: Config-Server

server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
