spring:
  cloud.config.server.git:
          clone-on-start: true
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          uri: ${spring.cloud.config.server.git.uri}

  application.name: Config-Server

server.port: 9999

eureka:
  client:
    service-url:
      defaultZone: ${eureka.client.service-url}
